# docker compose for forum flarum
---

services:

  mariadb:
    image: mariadb:10.11
    container_name: flarum_mariadb
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    volumes:
      - ./forum/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - flarum_net

  flarum:
    build: ./forum
    container_name: flarum
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./flarum.env
    volumes:
      - ./forum/flarum:/flarum/app
    labels:

      - "traefik.http.middlewares.flarum-timeout.timeout=60s"

      - "traefik.enable=true"
      - "traefik.http.routers.flarum.rule=Host(`forum.diplomania2.fr`)"
      - "traefik.http.routers.flarum.entrypoints=websecure"
      - "traefik.http.routers.flarum.tls=true"
      - "traefik.http.routers.flarum.tls.certresolver=myle"
      - "traefik.http.services.flarum.loadbalancer.server.port=9000"
    networks:
      - proxy
      - flarum_net

networks:
  proxy:
    external: true
  flarum_net:
    driver: bridge
