# docker compose for forum flarum
---

services:

  mariadb:
    image: mariadb:10.11
    container_name: flarum_mariadb
    restart: unless-stopped
    env_file:
      - ./flarum.env
    volumes:
      - ./forum/mariadb:/var/lib/mysql

  flarum:
    build: ./forum
    container_name: flarum
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ./forum/flarum/assets:/flarum/app/public/assets
      - ./forum/flarum/extensions:/flarum/app/extensions
      - ./forum/flarum/storage/logs:/flarum/app/storage/logs
      - ./forum/flarum/nginx:/etc/nginx/flarum
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flarum.rule=Host(`forum.diplomania2.fr`)"
      - "traefik.http.routers.flarum.entrypoints=websecure"
      - "traefik.http.routers.flarum.tls=true"
      - "traefik.http.routers.flarum.tls.certresolver=myle"
      - "traefik.http.services.flarum.loadbalancer.server.port=8888"
    networks:
      - proxy

networks:
  proxy:
    external: true
