# docker compose for forum flarum
---

services:

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 
    env_file:
      - ./mariadb.env
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - flarum_net

  flarum_app:
    build: ./php
    container_name: flarum_app
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./flarum.env
    volumes:
      # Local: ./flarum <==> Conteneur: /var/www/html (Chemin de travail PHP standard)
       - ./flarum/flarum:/var/www/html
    networks:
      - flarum_net

  flarum_nginx:
    image: nginx:stable-alpine
    container_name: flarum_nginx
    restart: unless-stopped
    depends_on:
      - flarum_app
    volumes:
      # VOLUME PARTAGÉ: Permet à Nginx de lire le code Flarum (doit correspondre à flarum_app)
      - ./flarum/flarum:/var/www/html
      - ./nginx/flarum.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flarum.rule=Host(`forum.diplomania2.fr`)"
      - "traefik.http.routers.flarum.entrypoints=websecure"
      - "traefik.http.routers.flarum.tls=true"
      - "traefik.http.routers.flarum.tls.certresolver=myle"
      - "traefik.http.services.flarum.loadbalancer.server.port=80"
    networks:
      - proxy
      - flarum_net

networks:
  proxy:
    external: true
  flarum_net:
    driver: bridge
