# docker compose for forum flarum
---

services:

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    volumes:
      - ./forum/mariadb:/var/lib/mysql
    networks:
      - flarum_net

  flarum:
    image: mondedie/flarum:latest
    container_name: flarum
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - ./flarum.env
    volumes:
      - ./forum/flarum/extensions:/flarum/app/public/extensions
      - ./forum/flarum/assets:/flarum/app/public/assets
      - ./forum/flarum/logs:/flarum/app/storage/logs
      - ./forum/flarum/etc/nginx/flarum:/etc/nginx/flarum
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flarum.rule=Host(`forum.diplomania2.fr`)"
      - "traefik.http.routers.flarum.entrypoints=websecure"
      - "traefik.http.routers.flarum.tls=true"
      - "traefik.http.routers.flarum.tls.certresolver=myle"
      - "traefik.http.services.flarum.loadbalancer.server.port=8888"
    networks:
      - proxy
      - flarum_net

networks:
  proxy:
    external: true
  flarum_net:
    driver: bridge
